// Place at: src/lib/tracker/modTypes.ts
//
// Modifications & accessories - one-off spend, not maintenance. No price
// benchmark (aftermarket part cost varies hugely by brand/quality) and no
// reminders (nothing wears out on a schedule) - just honest cost tracking.
//
// Expanded from a 635-item gear/parts catalog (Aug 2026). The original 17
// keys below are UNTOUCHED - two real accounts already have logged records
// pointing at these exact keys, so renaming or removing any of them would
// break their existing history. Everything past that point is additive.
// Items that duplicate an existing benchmarked Service job (tyres, brake
// pads, chain/sprockets, battery, spark plug, oil filter, air filter) were
// deliberately left out here, so there is exactly one place to log each of
// those - Service, not Mods.
export const MOD_LABELS: Record<string, string> = {
  "exhaust-headers": "Exhaust headers / downpipes",
  "exhaust-can": "Exhaust can / muffler",
  "suspension-upgrade": "Suspension upgrade",
  "tank-pads": "Tank pads / protectors",
  "decals-wrap": "Decals / wrap / graphics",
  "seat": "Seat (aftermarket/custom)",
  "crash-protection": "Crash protection (sliders, bars, bungs)",
  "screen": "Screen / windshield",
  "handlebars": "Handlebars / risers",
  "footpegs-rearsets": "Footpegs / rearsets",
  "mirrors": "Mirrors",
  "levers": "Levers (brake/clutch)",
  "luggage": "Luggage (panniers/top box/tank bag)",
  "lighting": "Lighting (LEDs, indicators)",
  "security": "Security (alarm, disc lock, tracker)",
  "custom-bespoke": "Custom/bespoke work",
  "other-accessory": "Other accessory",

  // --- Everything below added from the Aug 2026 catalog import ---
  "top-box": "Top box",
  "top-box-liner": "Top box liner",
  "side-case": "Side case",
  "side-case-liner": "Side case liner",
  "aluminium-pannier": "Aluminium pannier",
  "soft-pannier": "Soft pannier",
  "tank-bag": "Tank bag",
  "tail-bag": "Tail bag",
  "seat-bag": "Seat bag",
  "dry-bag": "Dry bag",
  "roll-bag": "Roll bag",
  "tool-roll": "Tool roll",
  "leg-bag": "Leg bag",
  "backpack": "Backpack",
  "hydration-backpack": "Hydration backpack",
  "saddle-bag": "Saddle bag",
  "fork-bag": "Fork bag",
  "handlebar-bag": "Handlebar bag",
  "bar-bag": "Bar bag",
  "map-case": "Map case",
  "luggage-net": "Luggage net",
  "cargo-net": "Cargo net",
  "bungee-cord": "Bungee cord",
  "rok-strap": "Rok strap",
  "tie-down-strap": "Tie-down strap",
  "inner-bag": "Inner bag",
  "mounting-plate": "Mounting plate",
  "quick-release-mount": "Quick-release mount",
  "tank-grip": "Tank grip",
  "phone-mount": "Phone mount",
  "gps-mount": "GPS mount",
  "usb-charger": "USB charger",
  "12v-socket": "12V socket",
  "battery-tender-lead": "Battery tender lead",
  "navigation-cradle": "Navigation cradle",
  "power-distribution-lead": "Power distribution lead",
  "cruise-control-aid": "Cruise control aid",
  "throttle-lock": "Throttle lock",
  "seat-cushion": "Seat cushion",
  "gel-seat-pad": "Gel seat pad",
  "air-cushion": "Air cushion",
  "luggage-rack": "Luggage rack",
  "top-box-mount": "Top box mount",
  "pannier-frame": "Pannier frame",
  "sissy-bar": "Sissy bar",
  "hand-guards": "Hand guards",
  "heated-grips": "Heated grips",
  "heated-seat": "Heated seat",
  "wind-deflector": "Wind deflector",
  "crash-bar-pads": "Crash bar pads",
  "throttle-assist": "Throttle assist",
  "seat-riser": "Seat riser",
  "lowering-kit": "Lowering kit",
  "footpeg-lowering-kit": "Footpeg lowering kit",
  "footpeg-rubber-insert": "Footpeg rubber insert",
  "palm-rest": "Palm rest",
  "bar-end-weights": "Bar end weights",
  "vibration-dampers": "Vibration dampers",
  "ergonomic-grips": "Ergonomic grips",
  "throttle-tube": "Throttle tube",
  "gear-lever": "Gear lever",
  "bar-end-mirror": "Bar end mirror",
  "steering-stem-nut": "Steering stem nut",
  "switch-cluster": "Switch cluster",
  "instrument-cluster": "Instrument cluster",
  "speedometer": "Speedometer",
  "tachometer": "Tachometer",
  "trip-computer": "Trip computer",
  "bluetooth-communicator": "Bluetooth communicator",
  "intercom": "Intercom",
  "headset": "Headset",
  "microphone": "Microphone",
  "speaker-kit": "Speaker kit",
  "action-camera": "Action camera",
  "camera-mount": "Camera mount",
  "dash-cam": "Dash cam",
  "gps-unit": "GPS unit",
  "gps-tracker": "GPS tracker",
  "phone-charger": "Phone charger",
  "wireless-charger": "Wireless charger",
  "heated-grip-controller": "Heated grip controller",
  "tpms-system": "TPMS system",
  "battery-monitor": "Battery monitor",
  "obd-reader": "OBD reader",
  "alarm-system": "Alarm system",
  "immobiliser": "Immobiliser",
  "usb-power-adapter": "USB power adapter",
  "auxiliary-light-switch": "Auxiliary light switch",
  "usb-c-cable": "USB-C cable",
  "12v-extension-lead": "12V extension lead",
  "parking-sensor": "Parking sensor",
  "rally-tripmeter": "Rally tripmeter",
  "disc-lock": "Disc lock",
  "chain-lock": "Chain lock",
  "u-lock": "U-lock",
  "ground-anchor": "Ground anchor",
  "wheel-clamp": "Wheel clamp",
  "alarm": "Alarm",
  "cover-lock": "Cover lock",
  "brake-lever-lock": "Brake lever lock",
  "thatcham-approved-lock": "Thatcham-approved lock",
  "anchor-plate": "Anchor plate",
  "security-cable": "Security cable",
  "lithium-battery": "Lithium battery",
  "regulator-rectifier": "Regulator rectifier",
  "cdi-unit": "CDI unit",
  "ecu": "ECU",
  "ignition-coil": "Ignition coil",
  "spark-plug-cap": "Spark plug cap",
  "starter-motor": "Starter motor",
  "alternator": "Alternator",
  "wiring-harness": "Wiring harness",
  "switchgear": "Switchgear",
  "sensor": "Sensor",
  "relay": "Relay",
  "fuse": "Fuse",
  "horn": "Horn",
  "indicator-relay": "Indicator relay",
  "starter-relay": "Starter relay",
  "voltage-regulator": "Voltage regulator",
  "kill-switch": "Kill switch",
  "ignition-switch": "Ignition switch",
  "headlight-bulb": "Headlight bulb",
  "tail-light-bulb": "Tail light bulb",
  "indoor-cover": "Indoor cover",
  "outdoor-cover": "Outdoor cover",
  "waterproof-cover": "Waterproof cover",
  "half-cover": "Half cover",
  "scooter-cover": "Scooter cover",
  "touring-bike-cover": "Touring bike cover",
  "dust-cover": "Dust cover",
  "pillion-seat-cover": "Pillion seat cover",
  "helmet-cover": "Helmet cover",
  "inner-tube": "Inner tube",
  "rim-tape": "Rim tape",
  "wheel-bearing": "Wheel bearing",
  "wheel-spacer": "Wheel spacer",
  "valve-stem": "Valve stem",
  "valve-cap": "Valve cap",
  "wheel-weight": "Wheel weight",
  "tyre-valve-tool": "Tyre valve tool",
  "tyre-pressure-gauge": "Tyre pressure gauge",
  "tyre-repair-plug": "Tyre repair plug",
  "chain-guide": "Chain guide",
  "chain-slider": "Chain slider",
  "chain-roller": "Chain roller",
  "drive-shaft": "Drive shaft",
  "cush-drive": "Cush drive",
  "chain-tensioner": "Chain tensioner",
  "countershaft-seal": "Countershaft seal",
  "steering-bearing": "Steering bearing",
  "linkage-bearing": "Linkage bearing",
  "oil-seal": "Oil seal",
  "o-ring": "O-ring",
  "seal-kit": "Seal kit",
  "bush-kit": "Bush kit",
  "needle-bearing": "Needle bearing",
  "race-bearing": "Race bearing",
  "tank-grips": "Tank grips",
  "frame-sliders": "Frame sliders",
  "crash-bobbins": "Crash bobbins",
  "fork-sliders": "Fork sliders",
  "swingarm-spools": "Swingarm spools",
  "radiator-guard": "Radiator guard",
  "headlight-protector": "Headlight protector",
  "tail-tidy": "Tail tidy",
  "number-plate-holder": "Number plate holder",
  "windshield-trim": "Windshield trim",
  "decal-kit": "Decal kit",
  "sticker-kit": "Sticker kit",
  "vinyl-wrap": "Vinyl wrap",
  "seat-cover": "Seat cover",
  "custom-graphics-kit": "Custom graphics kit",
  "engine-case-protector": "Engine case protector",
  "exhaust-heat-shield": "Exhaust heat shield",
  "handguard-protectors": "Handguard protectors",
  "fairing": "Fairing",
  "belly-pan": "Belly pan",
  "seat-cowl": "Seat cowl",
  "mudguard": "Mudguard",
  "fender": "Fender",
  "side-panel": "Side panel",
  "headlight-unit": "Headlight unit",
  "tail-light": "Tail light",
  "indicator": "Indicator",
  "radiator-shroud": "Radiator shroud",
  "subframe": "Subframe",
  "tail-section": "Tail section",
  "fairing-stay": "Fairing stay",
  "license-plate-light": "License plate light",
  "reflector": "Reflector",
  "side-stand-plate": "Side stand plate",
  "piston": "Piston",
  "piston-ring": "Piston ring",
  "cylinder": "Cylinder",
  "crankshaft": "Crankshaft",
  "connecting-rod": "Connecting rod",
  "main-bearing": "Main bearing",
  "camshaft": "Camshaft",
  "cam-chain": "Cam chain",
  "valve": "Valve",
  "valve-spring": "Valve spring",
  "valve-seal": "Valve seal",
  "head-gasket": "Head gasket",
  "gasket-kit": "Gasket kit",
  "timing-chain": "Timing chain",
  "oil-pump": "Oil pump",
  "water-pump": "Water pump",
  "clutch-kit": "Clutch kit",
  "clutch-basket": "Clutch basket",
  "pressure-plate": "Pressure plate",
  "gearbox": "Gearbox",
  "shift-fork": "Shift fork",
  "starter-clutch": "Starter clutch",
  "balancer-shaft": "Balancer shaft",
  "performance-air-filter": "Performance air filter",
  "airbox": "Airbox",
  "carburettor": "Carburettor",
  "carburettor-jet": "Carburettor jet",
  "fuel-pump": "Fuel pump",
  "fuel-injector": "Fuel injector",
  "fuel-filter": "Fuel filter",
  "fuel-tap": "Fuel tap",
  "throttle-body": "Throttle body",
  "velocity-stack": "Velocity stack",
  "fuel-line": "Fuel line",
  "fuel-cap": "Fuel cap",
  "intake-manifold": "Intake manifold",
  "idle-screw": "Idle screw",
  "throttle-cable": "Throttle cable",
  "choke-cable": "Choke cable",
  "full-exhaust-system": "Full exhaust system",
  "slip-on-exhaust": "Slip-on exhaust",
  "header-pipe": "Header pipe",
  "mid-pipe": "Mid pipe",
  "catalytic-converter": "Catalytic converter",
  "muffler": "Muffler",
  "exhaust-spring": "Exhaust spring",
  "heat-shield": "Heat shield",
  "exhaust-gasket": "Exhaust gasket",
  "o2-sensor": "O2 sensor",
  "exhaust-clamp": "Exhaust clamp",
  "exhaust-hanger": "Exhaust hanger",
  "fork": "Fork",
  "fork-spring": "Fork spring",
  "fork-seal": "Fork seal",
  "fork-bush": "Fork bush",
  "fork-oil": "Fork oil",
  "rear-shock": "Rear shock",
  "steering-damper": "Steering damper",
  "linkage": "Linkage",
  "swingarm-bearing": "Swingarm bearing",
  "shock-spring": "Shock spring",
  "preload-adjuster": "Preload adjuster",
  "fork-cap": "Fork cap",
  "dust-seal": "Dust seal",
  "brake-disc": "Brake disc",
  "brake-shoe": "Brake shoe",
  "caliper": "Caliper",
  "master-cylinder": "Master cylinder",
  "brake-hose": "Brake hose",
  "brake-line": "Brake line",
  "reservoir": "Reservoir",
  "brake-pedal": "Brake pedal",
  "abs-sensor": "ABS sensor",
  "brake-fluid-reservoir": "Brake fluid reservoir",
  "brake-caliper-seal": "Brake caliper seal",
  "brake-piston": "Brake piston",
  "brake-disc-bolts": "Brake disc bolts",
  "oem-bolt-kit": "OEM bolt kit",
  "stainless-bolt-kit": "Stainless bolt kit",
  "clip": "Clip",
  "rivet": "Rivet",
  "washer": "Washer",
  "nut": "Nut",
  "spacer": "Spacer",
  "rubber-grommet": "Rubber grommet",
  "cotter-pin": "Cotter pin",
  "split-pin": "Split pin",
  "hose-clamp": "Hose clamp",
  "cable-tie": "Cable tie",
  "threaded-insert": "Threaded insert",
  "retaining-clip": "Retaining clip",
  "spring-washer": "Spring washer",
  "lock-nut": "Lock nut",
  "passenger-backrest": "Passenger backrest",
  "passenger-seat": "Passenger seat",
  "passenger-grab-rail": "Passenger grab rail",
  "passenger-footpeg": "Passenger footpeg",
  "passenger-armrest": "Passenger armrest",
  "passenger-helmet-communicator": "Passenger helmet communicator",
  "passenger-rain-cover": "Passenger rain cover",
};

export interface ModSubgroup {
  subcategory: string;
  mods: string[];
}

export interface ModGroup {
  group: string;
  subgroups: ModSubgroup[];
}

// Each ORIGINAL group's "General" subgroup holds exactly the same items in
// the same order as the old flat MOD_GROUPS did - nothing about them moved
// or changed. Every subgroup after "General" is new, from the catalog import.
export const MOD_GROUPS: ModGroup[] = [
  {
    group: "Performance & exhaust",
    subgroups: [
      { subcategory: "General", mods: ["exhaust-headers", "exhaust-can", "suspension-upgrade"] },
      { subcategory: "Engine", mods: ["piston", "piston-ring", "cylinder", "crankshaft", "connecting-rod", "main-bearing", "camshaft", "cam-chain", "valve", "valve-spring", "valve-seal", "head-gasket", "gasket-kit", "timing-chain", "oil-pump", "water-pump", "clutch-kit", "clutch-basket", "pressure-plate", "gearbox", "shift-fork", "starter-clutch", "balancer-shaft"] },
      { subcategory: "Intake & fuel", mods: ["performance-air-filter", "airbox", "carburettor", "carburettor-jet", "fuel-pump", "fuel-injector", "fuel-filter", "fuel-tap", "throttle-body", "velocity-stack", "fuel-line", "fuel-cap", "intake-manifold", "idle-screw", "throttle-cable", "choke-cable"] },
      { subcategory: "Exhaust components", mods: ["full-exhaust-system", "slip-on-exhaust", "header-pipe", "mid-pipe", "catalytic-converter", "muffler", "exhaust-spring", "heat-shield", "exhaust-gasket", "o2-sensor", "exhaust-clamp", "exhaust-hanger"] },
    ],
  },
  {
    group: "Styling & protection",
    subgroups: [
      { subcategory: "General", mods: ["tank-pads", "decals-wrap", "seat", "crash-protection"] },
      { subcategory: "Styling & protection", mods: ["tank-grips", "frame-sliders", "crash-bobbins", "fork-sliders", "swingarm-spools", "radiator-guard", "headlight-protector", "tail-tidy", "number-plate-holder", "windshield-trim", "decal-kit", "sticker-kit", "vinyl-wrap", "seat-cover", "custom-graphics-kit", "engine-case-protector", "exhaust-heat-shield", "handguard-protectors"] },
      { subcategory: "Bodywork & lighting", mods: ["fairing", "belly-pan", "seat-cowl", "mudguard", "fender", "side-panel", "headlight-unit", "tail-light", "indicator", "radiator-shroud", "subframe", "tail-section", "fairing-stay", "license-plate-light", "reflector", "side-stand-plate"] },
    ],
  },
  {
    group: "Comfort & practicality",
    subgroups: [
      { subcategory: "General", mods: ["screen", "handlebars", "footpegs-rearsets", "mirrors", "levers", "luggage"] },
      { subcategory: "Luggage", mods: ["top-box", "top-box-liner", "side-case", "side-case-liner", "aluminium-pannier", "soft-pannier", "tank-bag", "tail-bag", "seat-bag", "dry-bag", "roll-bag", "tool-roll", "leg-bag", "backpack", "hydration-backpack", "saddle-bag", "fork-bag", "handlebar-bag", "bar-bag", "map-case", "luggage-net", "cargo-net", "bungee-cord", "rok-strap", "tie-down-strap", "inner-bag", "mounting-plate", "quick-release-mount"] },
      { subcategory: "Touring accessories", mods: ["tank-grip", "phone-mount", "gps-mount", "usb-charger", "12v-socket", "battery-tender-lead", "navigation-cradle", "power-distribution-lead", "cruise-control-aid", "throttle-lock", "seat-cushion", "gel-seat-pad", "air-cushion", "luggage-rack", "top-box-mount", "pannier-frame", "sissy-bar"] },
      { subcategory: "Comfort", mods: ["hand-guards", "heated-grips", "heated-seat", "wind-deflector", "crash-bar-pads", "throttle-assist", "seat-riser", "lowering-kit", "footpeg-lowering-kit", "footpeg-rubber-insert", "palm-rest", "bar-end-weights", "vibration-dampers", "ergonomic-grips"] },
      { subcategory: "Controls & cockpit", mods: ["throttle-tube", "gear-lever", "bar-end-mirror", "steering-stem-nut", "switch-cluster", "instrument-cluster", "speedometer", "tachometer", "trip-computer"] },
    ],
  },
  {
    group: "Electronics & security",
    subgroups: [
      { subcategory: "General", mods: ["lighting", "security"] },
      { subcategory: "Electronics", mods: ["bluetooth-communicator", "intercom", "headset", "microphone", "speaker-kit", "action-camera", "camera-mount", "dash-cam", "gps-unit", "gps-tracker", "phone-charger", "wireless-charger", "heated-grip-controller", "tpms-system", "battery-monitor", "obd-reader", "alarm-system", "immobiliser", "usb-power-adapter", "auxiliary-light-switch", "usb-c-cable", "12v-extension-lead", "parking-sensor", "rally-tripmeter"] },
      { subcategory: "Security", mods: ["disc-lock", "chain-lock", "u-lock", "ground-anchor", "wheel-clamp", "alarm", "cover-lock", "brake-lever-lock", "thatcham-approved-lock", "anchor-plate", "security-cable"] },
      { subcategory: "Electrical parts", mods: ["lithium-battery", "regulator-rectifier", "cdi-unit", "ecu", "ignition-coil", "spark-plug-cap", "starter-motor", "alternator", "wiring-harness", "switchgear", "sensor", "relay", "fuse", "horn", "indicator-relay", "starter-relay", "voltage-regulator", "kill-switch", "ignition-switch", "headlight-bulb", "tail-light-bulb"] },
    ],
  },
  {
    group: "Covers",
    subgroups: [
      { subcategory: "Covers", mods: ["indoor-cover", "outdoor-cover", "waterproof-cover", "half-cover", "scooter-cover", "touring-bike-cover", "dust-cover", "pillion-seat-cover", "helmet-cover"] },
    ],
  },
  {
    group: "Drivetrain & wheels",
    subgroups: [
      { subcategory: "Wheels & tyre accessories", mods: ["inner-tube", "rim-tape", "wheel-bearing", "wheel-spacer", "valve-stem", "valve-cap", "wheel-weight", "tyre-valve-tool", "tyre-pressure-gauge", "tyre-repair-plug"] },
      { subcategory: "Drivetrain", mods: ["chain-guide", "chain-slider", "chain-roller", "drive-shaft", "cush-drive", "chain-tensioner", "countershaft-seal"] },
      { subcategory: "Bearings & seals", mods: ["steering-bearing", "linkage-bearing", "oil-seal", "o-ring", "seal-kit", "bush-kit", "needle-bearing", "race-bearing"] },
    ],
  },
  {
    group: "Suspension & brakes",
    subgroups: [
      { subcategory: "Suspension", mods: ["fork", "fork-spring", "fork-seal", "fork-bush", "fork-oil", "rear-shock", "steering-damper", "linkage", "swingarm-bearing", "shock-spring", "preload-adjuster", "fork-cap", "dust-seal"] },
      { subcategory: "Brakes", mods: ["brake-disc", "brake-shoe", "caliper", "master-cylinder", "brake-hose", "brake-line", "reservoir", "brake-pedal", "abs-sensor", "brake-fluid-reservoir", "brake-caliper-seal", "brake-piston", "brake-disc-bolts"] },
    ],
  },
  {
    group: "Hardware & fasteners",
    subgroups: [
      { subcategory: "Hardware", mods: ["oem-bolt-kit", "stainless-bolt-kit", "clip", "rivet", "washer", "nut", "spacer", "rubber-grommet", "cotter-pin", "split-pin", "hose-clamp", "cable-tie", "threaded-insert", "retaining-clip", "spring-washer", "lock-nut"] },
    ],
  },
  {
    group: "Passenger & pillion",
    subgroups: [
      { subcategory: "Passenger & pillion", mods: ["passenger-backrest", "passenger-seat", "passenger-grab-rail", "passenger-footpeg", "passenger-armrest", "passenger-helmet-communicator", "passenger-rain-cover"] },
    ],
  },
  {
    group: "Other",
    subgroups: [
      { subcategory: "General", mods: ["custom-bespoke", "other-accessory"] },
    ],
  },
];

// Given a category key (e.g. from an existing logged record), finds which
// top-level group it belongs to - used to initialize the Group select when
// editing a record that already has a category set, without needing to
// duplicate the group/subgroup structure search logic elsewhere.
export function findGroupForCategory(category: string): string {
  for (const g of MOD_GROUPS) {
    for (const sg of g.subgroups) {
      if (sg.mods.includes(category)) return g.group;
    }
  }
  return MOD_GROUPS[0].group;
}
