// Sitewide SEO wiring: the sitemap, the share tags every public page
// sends, and the internal links the footer and header give crawlers.
import { existsSync, readFileSync } from "fs";
import path from "path";
import { describe, expect, it, vi } from "vitest";

vi.mock("next/navigation", () => ({ usePathname: () => "/" }));

import sitemap from "@/app/sitemap";
import { pageMetadata } from "@/lib/seo/pageMetadata";
import { PRICE_GUIDES, priceGuidePath } from "@/lib/seo/priceGuides";
import { ROBOTS_DISALLOW } from "@/lib/seo/robotsPolicy";

const APP = path.join(process.cwd(), "src/app");

// A site path is real if a page file exists for it, or it's a price guide
// generated by the [slug] routes.
function routeExists(href: string): boolean {
  const clean = href.split(/[?#]/)[0];
  if (clean === "/") return existsSync(path.join(APP, "page.tsx"));
  if (existsSync(path.join(APP, clean, "page.tsx"))) return true;
  return Object.values(PRICE_GUIDES)
    .flat()
    .some((g) => priceGuidePath(g) === clean);
}

describe("sitemap", () => {
  const entries = sitemap();
  const paths = entries.map((e) => e.url.replace("https://roadverdict.co.uk", "") || "/");

  it("lists every price guide and both price-guide hubs", () => {
    for (const guide of Object.values(PRICE_GUIDES).flat()) {
      expect(paths).toContain(priceGuidePath(guide));
    }
    expect(paths).toContain("/cars/costs");
    expect(paths).toContain("/motorcycles/costs");
  });

  it("only lists real, public pages - once each", () => {
    expect(new Set(paths).size).toBe(paths.length);
    for (const p of paths) {
      expect(routeExists(p), p).toBe(true);
      expect(ROBOTS_DISALLOW.some((blocked) => p.startsWith(blocked)), p).toBe(false);
    }
  });

  it("gives real dates, not the time of the request", () => {
    // A day's slack: a date is a UK calendar day, which starts before
    // midnight UTC in summer.
    const latestAllowed = Date.now() + 24 * 60 * 60 * 1000;
    for (const e of entries) {
      const t = (e.lastModified as Date).getTime();
      expect(t).toBeLessThan(latestAllowed);
      expect((e.lastModified as Date).getUTCHours()).toBe(0);
    }
  });
});

describe("pageMetadata", () => {
  it("points a page's share tags at the page itself, not the homepage", () => {
    const meta = pageMetadata({ title: "Car Quote Checker", description: "d", path: "/cars/quote-checker" });
    expect(meta.alternates).toEqual({ canonical: "/cars/quote-checker" });
    expect(meta.openGraph).toMatchObject({ url: "https://roadverdict.co.uk/cars/quote-checker", title: "Car Quote Checker | RoadVerdict" });
    expect(meta.twitter).toMatchObject({ title: "Car Quote Checker | RoadVerdict" });
  });

  it("uses an exact title when the brand is already in it", () => {
    const meta = pageMetadata({ title: "RoadVerdict Pro: Plans", description: "d", path: "/pro", absoluteTitle: true });
    expect(meta.title).toEqual({ absolute: "RoadVerdict Pro: Plans" });
    expect(meta.openGraph).toMatchObject({ title: "RoadVerdict Pro: Plans", url: "https://roadverdict.co.uk/pro" });
  });

  it("is what every public page uses, so none inherits the homepage's share tags", () => {
    const pages = [
      "page.tsx", "motorcycles/page.tsx", "cars/page.tsx", "quote-checker/page.tsx", "cars/quote-checker/page.tsx",
      "cost-calculator/page.tsx", "cars/cost-calculator/page.tsx", "buying-guide/page.tsx", "cars/buying-guide/page.tsx",
      "guides/page.tsx", "guides/buying-a-used-car/page.tsx", "guides/buying-a-used-motorcycle/page.tsx",
      "guides/cost-of-owning-a-car/page.tsx", "guides/cost-of-owning-a-motorcycle/page.tsx", "mpg-calculator/page.tsx", "pro/page.tsx",
      "about/page.tsx", "privacy/page.tsx", "cars/costs/page.tsx", "motorcycles/costs/page.tsx",
      "cars/costs/[slug]/page.tsx", "motorcycles/costs/[slug]/page.tsx",
    ];
    for (const page of pages) {
      expect(readFileSync(path.join(APP, page), "utf8"), page).toContain("pageMetadata(");
    }
  });
});

describe("internal links", () => {
  function hrefsIn(file: string): string[] {
    const src = readFileSync(path.join(process.cwd(), file), "utf8");
    return [...src.matchAll(/href[=:]\s*["'](\/[^"'?#]*)["']/g)].map((m) => m[1]);
  }

  it("every fixed link in the footer, header and homepage points at a real page", () => {
    for (const file of ["src/components/SiteFooterLinks.tsx", "src/app/SiteHeaderNav.tsx", "src/app/page.tsx", "src/components/RelatedTools.tsx", "src/components/CarRelatedTools.tsx"]) {
      for (const href of hrefsIn(file)) {
        if (href.startsWith("/login")) continue;
        expect(routeExists(href), `${file}: ${href}`).toBe(true);
      }
    }
  });

  it("links the homepage to both vehicle hubs and both sets of price guides", () => {
    const hrefs = hrefsIn("src/app/page.tsx");
    for (const href of ["/motorcycles", "/cars", "/motorcycles/costs", "/cars/costs"]) {
      expect(hrefs, href).toContain(href);
    }
  });
});
